# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  changedfiles-push:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} >> files_changed.txt
          cat files_changed.txt
      
      - name: Set up Python 3.8.2
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.2"

      - name: Install sqlfluff
        run: |
          pip install sqlfluff
      - name: Test Syntax of Changed sql files
        run: python3 .github/workflows/test_sql_files.py files_changed.txt
